- Dockerfile
fixes eclipse-xpanse/xpanse#716
> provide docker file

- .github/workflows/release.yml
- jreleaser.yml
fixes eclipse-xpanse/xpanse#717
> provide release build

- .github/workflows/release.yml
- Dockerfile
- jreleaser.yml
> update maven command

- Dockerfile
> revert file rename

- src/main/java/org/eclipse/xpanse/terraform/boot/api/TerraformApiController.java
- src/main/java/org/eclipse/xpanse/terraform/boot/models/TerraformBootSystemStatus.java
- src/main/java/org/eclipse/xpanse/terraform/boot/terraform/TerraformExecutor.java
related to eclipse-xpanse/xpanse#812
> Rename SystemStatus to TerraformBootSystemStatus

- src/main/java/org/eclipse/xpanse/terraform/boot/api/TerraformApiController.java
- src/main/java/org/eclipse/xpanse/terraform/boot/terraform/service/TerraformScriptsService.java
Fixed eclipse-xpanse/xpanse#760
> implement terraform-boot for validate method 

- src/main/java/org/eclipse/xpanse/terraform/boot/terraform/TerraformExecutor.java
Fixed eclipse-xpanse/xpanse#838
> Validation request to terraform-boot fails

- README.md
- pom.xml
- src/main/java/org/eclipse/xpanse/terraform/boot/models/response/ResultType.java
- src/main/java/org/eclipse/xpanse/terraform/boot/security/oauth2/config/Oauth2Constants.java
- src/main/java/org/eclipse/xpanse/terraform/boot/security/oauth2/config/Oauth2OpenApiConfig.java
- src/main/java/org/eclipse/xpanse/terraform/boot/security/oauth2/config/Oauth2WebSecurityConfig.java
- src/main/java/org/eclipse/xpanse/terraform/boot/security/oauth2/introspector/OauthOpaqueTokenIntrospector.java
- src/main/resources/application-oauth.properties
fixes eclipse-xpanse/xpanse#714
> Enable conditional oauth authentication for terraform-boot

- src/main/java/org/eclipse/xpanse/terraform/boot/terraform/service/TerraformDirectoryService.java
- src/main/java/org/eclipse/xpanse/terraform/boot/terraform/service/TerraformScriptsService.java
Fixed eclipse-xpanse/xpanse#847
> terraform-boot does not call webhook in case of failure

- README.md
- src/main/java/org/eclipse/xpanse/terraform/boot/security/oauth2/config/Oauth2WebSecurityConfig.java
- src/main/resources/application-oauth.properties
Fixed eclipse-xpanse/xpanse#882
> terraform-boot oauth with JWT fails

- .github/workflows/release.yml
Revert token changes suggested by EF
> revert back to use bot token

- pom.xml
reset version to do a fresh stable release with correct assets.
> reset version

- pom.xml
- src/main/java/org/eclipse/xpanse/terraform/boot/api/TerraformApiController.java
- src/main/java/org/eclipse/xpanse/terraform/boot/models/plan/TerraformPlan.java
- src/main/java/org/eclipse/xpanse/terraform/boot/models/plan/TerraformPlanFromDirectoryRequest.java
- src/main/java/org/eclipse/xpanse/terraform/boot/models/plan/TerraformPlanWithScriptsRequest.java
- src/main/java/org/eclipse/xpanse/terraform/boot/models/request/TerraformDeployWithScriptsRequest.java
- src/main/java/org/eclipse/xpanse/terraform/boot/terraform/TerraformExecutor.java
- src/main/java/org/eclipse/xpanse/terraform/boot/terraform/service/TerraformDirectoryService.java
- src/main/java/org/eclipse/xpanse/terraform/boot/terraform/service/TerraformScriptsService.java
fixes https://github.com/eclipse-xpanse/xpanse/issues/926
> add terraform plan generation methods

- .github/workflows/release.yml
- pom.xml
> fix release job

- .github/workflows/release.yml
related to - https://github.com/eclipse-xpanse/xpanse/issues/930
fix release job
> add missing keys for signing

- jreleaser.yml
related to https://github.com/eclipse-xpanse/xpanse/issues/935
> skip merge commits from changelog

- .github/workflows/ci.yml
- .github/workflows/release.yml
- pom.xml
fixes https://github.com/eclipse-xpanse/xpanse/issues/965
> upgrade to java 21

- src/main/java/org/eclipse/xpanse/terraform/boot/api/TerraformApiController.java
- src/main/java/org/eclipse/xpanse/terraform/boot/terraform/service/TerraformScriptsService.java
Fixed eclipse-xpanse/xpanse#1047
> add custom requestId header option to terraform-boot

- Dockerfile
related to https://github.com/eclipse-xpanse/xpanse/issues/1079
> fix jdk21 base image

- src/main/java/org/eclipse/xpanse/terraform/boot/terraform/TerraformExecutor.java
- src/main/resources/application.properties
fixes https://github.com/eclipse-xpanse/xpanse/issues/1094
> fix module default path logic and config

- jreleaser.yml
related to https://github.com/eclipse-xpanse/xpanse/issues/1102
> update contributor information

- README.md
- pom.xml
- src/main/java/org/eclipse/xpanse/terraform/boot/observability/OpenTelemetryConfiguration.java
- src/main/resources/application-opentelemetry.properties
- src/main/resources/application.properties
- src/main/resources/logback.xml
fixes https://github.com/eclipse-xpanse/xpanse/issues/1100
> provide option to enable opentelemetry metrics

- .github/workflows/license-checks.yml
- DEPENDENCIES
- pom.xml
related to https://github.com/eclipse-xpanse/xpanse/issues/1148
> add dash tool job

- src/main/java/org/eclipse/xpanse/terraform/boot/models/enums/DestroyScenario.java
- src/main/java/org/eclipse/xpanse/terraform/boot/models/request/directory/TerraformDestroyFromDirectoryRequest.java
- src/main/java/org/eclipse/xpanse/terraform/boot/models/response/TerraformResult.java
- src/main/java/org/eclipse/xpanse/terraform/boot/terraform/service/TerraformDirectoryService.java
fixes https://github.com/eclipse-xpanse/xpanse/issues/1301
related to https://github.com/eclipse-xpanse/xpanse/pull/1326
> fix error state when rollback success

- pom.xml
- src/main/java/org/eclipse/xpanse/terraform/boot/TerraformBootApplication.java
- src/main/java/org/eclipse/xpanse/terraform/boot/api/controllers/TerraformBootFromDirectoryApi.java
- src/main/java/org/eclipse/xpanse/terraform/boot/api/controllers/TerraformBootFromGitRepoApi.java
- src/main/java/org/eclipse/xpanse/terraform/boot/api/controllers/TerraformBootFromScriptsApi.java
- src/main/java/org/eclipse/xpanse/terraform/boot/logging/CustomRequestIdGenerator.java
- src/main/java/org/eclipse/xpanse/terraform/boot/models/plan/TerraformPlanFromDirectoryRequest.java
- src/main/java/org/eclipse/xpanse/terraform/boot/models/request/directory/TerraformDeployFromDirectoryRequest.java
- src/main/java/org/eclipse/xpanse/terraform/boot/models/request/directory/TerraformDestroyFromDirectoryRequest.java
- src/main/java/org/eclipse/xpanse/terraform/boot/models/request/directory/TerraformModifyFromDirectoryRequest.java
- src/main/java/org/eclipse/xpanse/terraform/boot/models/request/scripts/TerraformModifyWithScriptsRequest.java
- src/main/java/org/eclipse/xpanse/terraform/boot/models/response/TerraformResult.java
- src/main/java/org/eclipse/xpanse/terraform/boot/terraform/service/ScriptsGitRepoManage.java
- src/main/java/org/eclipse/xpanse/terraform/boot/terraform/service/TerraformDirectoryService.java
- src/main/java/org/eclipse/xpanse/terraform/boot/terraform/service/TerraformGitRepoService.java
- src/main/java/org/eclipse/xpanse/terraform/boot/terraform/service/TerraformScriptsService.java
- src/main/resources/logback.xml
fixes https://github.com/eclipse-xpanse/xpanse/issues/1602
Related to https://github.com/eclipse-xpanse/xpanse/pull/1621
> Add UUID to record the request

- src/main/java/org/eclipse/xpanse/terraform/boot/logging/CustomRequestIdGenerator.java
- src/main/resources/logback.xml
fixes https://github.com/eclipse-xpanse/xpanse/issues/1633
> Add the TRACKING_ID and REQUEST_ID to the logs

- src/main/java/org/eclipse/xpanse/terraform/boot/terraform/service/TerraformDirectoryService.java
Fixed https://github.com/eclipse-xpanse/xpanse/issues/1831
Related to https://github.com/eclipse-xpanse/xpanse/pull/1835 and https://github.com/eclipse-xpanse/tofu-maker/pull/44
> Clean up files have been read in workspace

- src/main/java/org/eclipse/xpanse/terraform/boot/terraform/tool/TerraformVersionsHelper.java
Fixed https://github.com/eclipse-xpanse/xpanse/issues/2038
Related to https://github.com/eclipse-xpanse/tofu-maker/pull/71
> Fix error when default terraform used

- pom.xml
- src/main/java/org/eclipse/xpanse/terraform/boot/api/controllers/TerraformBootTaskResultApi.java
- src/main/java/org/eclipse/xpanse/terraform/boot/models/exceptions/ResultAlreadyReturnedOrRequestIdInvalidException.java
- src/main/java/org/eclipse/xpanse/terraform/boot/models/exceptions/TerraformApiExceptionHandler.java
- src/main/java/org/eclipse/xpanse/terraform/boot/models/response/ResultType.java
- src/main/java/org/eclipse/xpanse/terraform/boot/terraform/service/TerraformDirectoryService.java
- src/main/java/org/eclipse/xpanse/terraform/boot/terraform/service/TerraformGitRepoService.java
- src/main/java/org/eclipse/xpanse/terraform/boot/terraform/service/TerraformResultPersistenceManage.java
- src/main/java/org/eclipse/xpanse/terraform/boot/terraform/service/TerraformScriptsService.java
- src/main/java/org/eclipse/xpanse/terraform/boot/utils/TerraformResultSerializer.java
- src/main/resources/application.properties
Fixed eclipse-xpanse/xpanse#2079
> implement refetch of request result from terraform-boot in case of callback failures

- src/main/java/org/eclipse/xpanse/terraform/boot/api/controllers/TerraformBootTaskResultApi.java
- src/main/java/org/eclipse/xpanse/terraform/boot/terraform/service/TerraformResultPersistenceManage.java
Fixed eclipse-xpanse/xpanse#2131
> handle still in-progress requests in getStoredTaskResultByRequestId

- pom.xml
- src/main/java/org/eclipse/xpanse/terraform/boot/security/oauth2/config/Oauth2JwtDecoder.java
- src/main/java/org/eclipse/xpanse/terraform/boot/security/oauth2/config/Oauth2WebSecurityConfig.java
- src/main/java/org/eclipse/xpanse/terraform/boot/security/oauth2/introspector/OauthOpaqueTokenIntrospector.java
Fixed https://github.com/eclipse-xpanse/xpanse/issues/2178
Related to https://github.com/eclipse-xpanse/xpanse/pull/2181
Related to https://github.com/eclipse-xpanse/tofu-maker/pull/89
> Add retry for JWT auth to avoid application startup failed

- src/main/java/org/eclipse/xpanse/terraform/boot/terraform/service/TerraformDirectoryService.java
- src/main/java/org/eclipse/xpanse/terraform/boot/terraform/service/TerraformScriptsHelper.java
- src/main/java/org/eclipse/xpanse/terraform/boot/terraform/tool/TerraformVersionsHelper.java
Fixed https://github.com/eclipse-xpanse/xpanse/issues/2254
Related to https://github.com/eclipse-xpanse/xpanse/pull/2256
> handle errors when processing deployment result

- README.md
- pom.xml
- src/main/java/org/eclipse/xpanse/terraform/boot/config/RestTemplateConfig.java
- src/main/java/org/eclipse/xpanse/terraform/boot/logging/RestTemplateLoggingInterceptor.java
- src/main/java/org/eclipse/xpanse/terraform/boot/security/hmac/HmacSignatureHeaderInterceptor.java
- src/main/java/org/eclipse/xpanse/terraform/boot/security/hmac/HmacSignatureHeaderManage.java
- src/main/resources/application-dev.properties
- src/main/resources/application.properties
- src/test/java/org/eclipse/xpanse/terraform/boot/terraform/tool/HmacSignatureHeaderTest.java
fixes https://github.com/eclipse-xpanse/xpanse/issues/2365
> enable HMAC based webhook request signing

- pom.xml
- src/test/java/org/eclipse/xpanse/terra/boot/terraform/tool/TerraformInstallerTest.java
fixes https://github.com/eclipse-xpanse/xpanse/issues/2316
> Add similar test but with GitHub API mocked with wiremock.
